#%RAML 1.0
title: ILL Requesting Agency Storage
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Interlibrary Loan Requesting Agency Storage API
    content: <b>Storage API for an interlibrary loans requesting agency</b>

types:
  submission:    !include mod-ill-ramls/schemas/submission/submission.json
  submissions:   !include mod-ill-ramls/schemas/submission/submissions.json
  submissionStatus:     !include mod-ill-ramls/schemas/submission-status/submission-status.json
  submissionStatuses:   !include mod-ill-ramls/schemas/submission-status/submission-statuses.json
  saMessage: !include mod-ill-ramls/schemas/supplying-agency-message-storage/request/supplying-agency-message-storage-request.schema
  saMessages: !include mod-ill-ramls/schemas/supplying-agency-message-storage/request/supplying-agency-message-storage-requests.schema
  messageResponse: !include mod-ill-ramls/schemas/supplying-agency-message-storage/response/supplying-agency-message-storage-response.schema
  request:    !include mod-ill-ramls/schemas/request/request.json
  requests:   !include mod-ill-ramls/schemas/request/requests.json
  errors:     !include raml-util/schemas/errors.schema
  parameters: !include raml-util/schemas/parameters.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml

/ill-ra-storage:
  /submissions:
    displayName: Submissions
    type:
      collection:
        exampleCollection: !include mod-ill-ramls/examples/submission/submissions.json
        exampleItem: !include mod-ill-ramls/examples/submission/submission.json
        schemaCollection: submissions
        schemaItem: submission
    get:
      is: [pageable,
        searchable: {description: "searchable using CQL",
                        example: "id=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""},
        ]
      responses:
        501:
          description: "Not implemented yet"
    post:
      is: [validate]
    /{submissionId}:
      type:
        collection-item:
          exampleItem: !include mod-ill-ramls/examples/submission/submission.json
          schema: submission
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        is: [validate]
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
      /requests:
        type:
          collection:
            exampleCollection: !include mod-ill-ramls/examples/request/requests.json
            exampleItem: !include mod-ill-ramls/examples/request/request.json
            schemaCollection: requests
            schemaItem: request
        get:
          is: [pageable]
  /submission-statuses:
    displayName: Submission Statuses
    type:
      collection:
        exampleCollection: !include mod-ill-ramls/examples/submission-status/submission-statuses.json
        exampleItem: !include mod-ill-ramls/examples/submission-status/submission-status.json
        schemaCollection: submissionStatuses
        schemaItem: submissionStatus
    get:
      is: [pageable,
        searchable: {description: "searchable using CQL",
                        example: "id=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""},
        ]
    post:
      is: [validate]
    /{statusId}:
      type:
        collection-item:
          exampleItem: !include mod-ill-ramls/examples/submission-status/submission-status.json
          schema: submissionStatus
      get:
      put:
        is: [validate]
      delete:
  /requests:
    displayName: Requests
    type:
      collection:
        exampleCollection: !include mod-ill-ramls/examples/request/requests.json
        exampleItem: !include mod-ill-ramls/examples/request/request.json
        schemaCollection: requests
        schemaItem: request
    get:
      is: [pageable,
        searchable: {description: "searchable using CQL",
                        example: "id=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""},
        ]
      responses:
        501:
          description: "Not implemented yet"
    post:
      is: [validate]
    /{requestId}:
      type:
        collection-item:
          exampleItem: !include mod-ill-ramls/examples/request/request.json
          schema: request
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        is: [validate]
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
      /messages:
        displayName: A collection of supplier messages associated with a supplier request
        type:
          collection:
            exampleCollection: !include mod-ill-ramls/examples/message/message.json
            exampleItem: !include mod-ill-ramls/examples/message/message.json
            schemaCollection: saMessages
            schemaItem: saMessage
        get:
          responses:
            501:
              description: "Not implemented yet"
  /messages:
    displayName: Messages
    description: Supplying Agency Messages
    type:
      collection:
        exampleCollection: !include mod-ill-ramls/examples/message/messages.json
        exampleItem: !include mod-ill-ramls/examples/message/message.json
        schemaCollection: saMessages
        schemaItem: saMessage
    get:
      is: [pageable,
        searchable: {description: "searchable using CQL",
                        example: "id=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""},
        ]
      responses:
        501:
          description: "Not implemented yet"
    post:
      is: [validate]
